apiVersion: v1
kind: Service
metadata:
  name: {{ include "qv.fullname" . }}
  labels: {{- include "qv.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "qv.selectorLabels" . | nindent 4 }}
  # Headless service component for the StatefulSet's stable DNS names.
  clusterIP: None
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
